### ISSUE TITLE
Not supported utf-8 validation

### ISSUE THREAD

**Issue by captainhamid** [proengsoft/laravel-jsvalidation#200]
when use validation persian number, We deal with errors Invalid regular expression.
```
'mobile' => array('required', 'regex:/^09[0-3][0-9]{8}|^\x{06F0}\x{06F9}[\x{06F0}-\x{06F3}][\x{06F0}-\x{06F9}]{8}$/'),
```
when use \uXXXX instead \x{XXXX}, client validation is correct but error in server,
error server: Compilation failed: PCRE does not support \L, \l, \N{name}, \U, or \u

http://stackoverflow.com/questions/3538293/php-regular-expression-pcre-does-not-support-l-l-n-p

**Comment by captainhamid** [comment]
please, pay attention.

**Comment by a-komarev** [comment]
@captainhamid have you found any solution for it? I would be able to dig into validation rules updates in a couple of months.

**Comment by bytestream** [comment]
JS regex engine is missing features that exist in PCRE. I'd suggest to make regex validation use AJAX so it's validated on the server (using PCRE). I did start writing a custom validation rule to force js validation to use AJAX but it's pretty messy because Laravel has this hard-coded check in the Validator:
````php
protected function parseParameters($rule, $parameter)
{
    if (strtolower($rule) == 'regex') {
        return [$parameter];
    }

    return str_getcsv($parameter);
}
````

In the end I just opted to disable js validation on the field `no_js_validation`...

**Comment by bytestream** [comment]
Suggest to just use `no_js_validation` on regex rules unless someone wants to submit a PR.
