### ISSUE TITLE
Support Bootstrap 4.1

### ISSUE THREAD

**Issue by Braunson** [proengsoft/laravel-jsvalidation#321]
Is support for Bootstrap 4 in the pipeline? It doesn't look like the GH project has been updated in a year?

I'd be willing to put in a PR for this if nobody hasn't started on it already.

**Comment by a-komarev** [comment]
@Braunson here are some workaround: #306

You could make changes in your own application or make Pull Request. I think everybody will be happy to see this changes out of the box!

**Comment by X-Coder** [comment]
#325 contains a little bug causing wrong class names on the input elements and not working coloring.

In bootstrap4.php all "form.control" classes needs to be replaced by "form-control" (replace point to dash).

When this gets fixed, also the commented unhighlight lines has to be enabled, because the is-invalid need to be cleared then from the inputs when validation changes to valid.

**Comment by antonkomarev** [comment]
Fixed in #354
