### ISSUE TITLE
Outdated phpjs implementation 

### ISSUE THREAD

**Issue by Nuranto** [proengsoft/laravel-jsvalidation#444]
after_or_equal / before_or_equal does not work with `today` keyword (`before_or_equal:today`). Probably with other keywords as well.
Error is : 
```
jsvalidation.js:1047 Uncaught TypeError: string.replace is not a function.  Exception occurred when checking element date_of_birth, check the 'laravelValidation' method.
```

Probably the problem occurs on Before/After too ?

**Comment by bytestream** [comment]
Thanks @Nuranto 

At a glance, I think because we're using such an old version of `phpjs` it doesn't support `today`.  We'd need to upgrade to the latest version which looks more promising: https://github.com/kvz/locutus/blob/master/src/php/datetime/strtotime.js#L1066

The only issue is that there's quite a few uses of `phpjs` so the likelihood of something breaking is probable!

I'll take a PR which upgrades `phpjs`

**Comment by bytestream** [comment]
Check the lniked PR @Nuranto

**Comment by spyrmpontinis** [comment]
Hello i a having the same problem. Any news for the fix.
![image](https://user-images.githubusercontent.com/4165165/82341498-2aab5780-99f9-11ea-8962-88fa0185b9b0.png)

The problem is happening because the rule validator for some reason is array as you can see in the printscreen.

**Comment by spyrmpontinis** [comment]
I have the same problem in the after 
![image](https://user-images.githubusercontent.com/4165165/82342068-db195b80-99f9-11ea-9cdd-9648e8d76b9c.png)

**Comment by bytestream** [comment]
@spyrmpontinis that issue sounds different to what's described in this issue?

You're comparing against another field. This issue is regarding an outdated strtotime implementation so certain date keywords don't work correctly.

If that's not working, please try to debug and open a new issue.

**Comment by bytestream** [comment]
@Nuranto if I merge to master do you mind checking it?

**Comment by bert-w** [comment]
@bytestream thats not how git branches should work...

fwiw i just encountered this issue. I'm using the Laravel validation `before_or_after:now`. It causes an error in the `escapeCssMeta` function because it receives an array `["date"]` instead of a string. Havent checked any further on what it's actually doing.

Error message:
```
// jsvalidation.js:1047:18

TypeError: string.replace is not a function.  Exception occurred when checking element , check the 'laravelValidation' method.
```

**Comment by bytestream** [comment]
> @bytestream thats not how git branches should work...

`dev-master` is not stable, only releases are stable. As far as I'm concerned the functionality in the PR works but I would appreciate others confirming.

> fwiw i just encountered this issue. I'm using the Laravel validation `before_or_after:now`. It causes an error in the `escapeCssMeta` function because it receives an array `["date"]` instead of a string. 

This sounds more related to https://github.com/proengsoft/laravel-jsvalidation/issues/424#issuecomment-600246975 than this issue... 

Please open a new issue with a full test case to replicate.

This issue is specifically an outdated phpjs implementation. Anything else pertaining to after_/before_ rules should be opened in another issue with minimal test cases.

**Comment by garbinmarcelo** [comment]
> I have the same problem in the after
> ![image](https://user-images.githubusercontent.com/4165165/82342068-db195b80-99f9-11ea-9cdd-9648e8d76b9c.png)

Hello, did you solve it? I'm going through something similar, but with "after_or_equal"

**Comment by spyrmpontinis** [comment]
> 
> 
> > I have the same problem in the after
> > ![image](https://user-images.githubusercontent.com/4165165/82342068-db195b80-99f9-11ea-9cdd-9648e8d76b9c.png)
> 
> Hello, did you solve it? I'm going through something similar, but with "after_or_equal"

Hello , i did not fix it in frontend. I am doing the validation on save controller because the problem is on jquery.validate.js as you can see in the print screen on js debugger of firefox.  

![image](https://user-images.githubusercontent.com/4165165/103389008-feba8d80-4b14-11eb-8285-f53689773a86.png)

The problem is that jsvalidation.js on line 94 on rule "after" or "after_or_equals" in your case the element param[1] is array as you can see on my print screen. 

![image](https://user-images.githubusercontent.com/4165165/103389216-3e35a980-4b16-11eb-9457-fcb85d5d71e8.png)

So the jquery.vaidate.js on is trying to use replace function on array which is not exists. I hope i was helpfull . I wish you happy new year :)

**Comment by bytestream** [comment]
Please open a new issue if you can replicate on the latest version. https://github.com/proengsoft/laravel-jsvalidation/issues/530 was very similar to what you describe
