### ISSUE TITLE
FormRequest::rules() allow type-hint any dependencies but not JsValidator::formRequest

### ISSUE THREAD

**Issue by thewebartisan7** [proengsoft/laravel-jsvalidation#495]
### Subject of the issue
 You may type-hint any dependencies you need within the rules method's signature of FormRequest. They will automatically be resolved via the Laravel service container.

### Your environment
* version of this package: 4.2
* version of Laravel: 7.x

### Steps to reproduce
If your FormRequest method rules() has dependencies as allowed by FormRequest rules() methods then you can use it with `{!! JsValidator::formRequest(['App\Http\Requests\MyFormRequest']) !!}`

### Expected behaviour
Would be good that is possible to pass an array as first param, where first item of array is FormRequest and any additional is the dependencies passed to rules() method.

### Actual behaviour
Actually happen an error that missing dependencies.

```
    public function formRequest($formRequest, $selector = null)
    {
        $deps = null;
        if (is_array($formRequest)) {
            $fr = $formRequest[0];
            $deps = array_shift($formRequest);
            $formRequest = $fr;
        }
     
        // Now we may have or not $deps

        if (! is_object($formRequest)) {
            $formRequest = $this->createFormRequest($formRequest);
        }

        $rules = method_exists($formRequest, 'rules') ? $formRequest->rules($deps) : [];

        //... other as now
    }
```

Am I missing something?

**Comment by bytestream** [comment]
Hey. None of the method calls in `formRequest` are resolved via the container so that would be the issue:
https://github.com/proengsoft/laravel-jsvalidation/blob/master/src/JsValidatorFactory.php#L134

It should probably be:
```php
$this->app->call([$formRequest, 'rules'])
```

At a quick glance it looks like `app->call` exists in Laravel 5.6 (https://github.com/laravel/framework/blob/5.6/src/Illuminate/Container/Container.php#L562) so I think it should be safe to add.

You're welcome to submit a PR.

**Comment by thewebartisan7** [comment]
I see what you mean.
This should be enough:
https://github.com/proengsoft/laravel-jsvalidation/pull/496

What you think?
