### ISSUE TITLE
Posible error on remote validation of unique email on update

### ISSUE THREAD

**Issue by drjoju** [proengsoft/laravel-jsvalidation#78]
Hi Albert,

I trying to do this validation on a FormRequest on a update method of a controller.

'contacto.email' => 'email|unique:users,email,id,'.$this->segment(2),

The url is something like
http://proyect.dev/clientes/401/edit

I try too 
'contacto.email' => 'email|unique:users,email,id,'.$this->get('id'),
Because the method is
 public function update(ClientesRequest $request, $id) 

I get an error 
QueryException in Connection.php line 636:
SQLSTATE[42S22]: Column not found: 1054 Unknown column '401' in 'where clause' (SQL: select count(*) as aggregate from `gs_users` where `email` = aaaa.xxxxxx@yahoo.com and `401` <> id)

As you see, the query is extrange. I thik is a problem of Laravel. 

What do you think?

Best regards

**Comment by torrentalle** [comment]
I think that your rule syntaxt is wrong.
From laravel documentation:

>**Forcing A Unique Rule To Ignore A Given ID:**
Sometimes, you may wish to ignore a given ID during the unique check. For example, consider an "update profile" screen that includes the user's name, e-mail address, and location. Of course, you will want to verify that the e-mail address is unique. However, if the user only changes the name field and not the e-mail field, you do not want a validation error to be thrown because the user is already the owner of the e-mail address. You only want to throw a validation error if the user provides an e-mail address that is already used by a different user. To tell the unique rule to ignore the user's ID, you may pass the ID as the third parameter:
'email' => 'unique:users,email_address,'.$user->id

The correct syntaxt should be:

'contacto.email' => 'email|unique:users,email,'.$this->segment(2),

**Comment by torrentalle** [comment]
Just another think. You should use *dev-master* version, because *v1.1.4* version has a bug with array named fields.
