### ISSUE TITLE
Multiple Instances of JSValidation

### ISSUE THREAD

**Issue by heikobihlmaier** [proengsoft/laravel-jsvalidation#87]
Hello!

In my account controller I have 2 validations for 2 forms.

I make JSValidation second times with another variable names and include both into the render function.

But in testing I become second times the same validation.

Example:

I define Validation a and Validation B.

In the view I geht validation b and validation b.

But I render Validation a and Validation b.

Can u help this ?

**Comment by torrentalle** [comment]
I'm going to make some tests about this issue.

Sorry for late response,

**Comment by derekmd** [comment]
`Proengsoft\JsValidation\JsValidatorFactory` contains one `Proengsoft\JsValidation\Manager` instance shared by each call to `JsValidator::make()` or `JsValidator::formRequest()` (via the facade.)

So in `JsValidatorFactory::jsValidator()`, calling

```php
    $this->manager->selector($selector);
    $this->manager->setValidator($validator);
```

is overwriting the previous jQuery Validator Plugin configuration.

It'll have to be refactored to permit multiple instance of `Manager` (which in a way is the controller that generates data for the view.) Since `$selector` and `$view` passed into the `Manager` constructor are primitive types, you don't require a deep copy to do this. Since it's better practice to keep references to the configuration file in your service provider, keep that constructor code as-is but later use PHP's `clone` operation for each `JsValidator` instance.

In `JsValidatorFactory`, you just need to change the `jsValidator()` method:

```php
    protected function jsValidator(Validator $validator, $selector = null)
    {
        $manager = clone $this->manager;

        $manager->selector($selector);
        $manager->setValidator($validator);

        return $manager;
    }
```

**Comment by torrentalle** [comment]
Thank's for this fix, I will release it son
 :smile:
